# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingParticipator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='participators',
        ),
        migrations.AddField(
            model_name='meetingparticipator',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Meeting'),
        ),
        migrations.AddField(
            model_name='meetingparticipator',
            name='participator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.User'),
        ),
    ]
